from sqlalchemy import text

from ai_bi_assistant.database.connection import engine


def execute_sql(sql: str):
    """
    Execute SQL generated by the LLM.
    """

    with engine.connect() as conn:
        result = conn.execute(text(sql))

    return [dict(row) for row in result.mappings()]